spring:
  application:
    name: GettingStart
#  jackson:
#    time-zone: UTC
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/sbdt_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&tinyInt1isBit=false"
    username: root
    password: 1234
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-sbdt_db
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: true
           
  config:
    import: classpath:users.properties  
    
management:
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    enable:
      sql: true
    export:
      prometheus:
        enable: true
